### ISSUE TITLE
Kabré! 0.Hola mundo. 1.Correr Zylo.

### ISSUE THREAD

**Issue by fabianfallasmoya** [fabianfallasmoya/agro#1]

**Comment by ManfredGonzalez** [comment]
Ya corrí el hola mundo de pytorch en Kabré, era un clasificador de imágenes sumamente básico, con una arquitectura de red convolucional pequeñita. Funcionó bastante bien y además, me corrobora que el ambiente conda que tengo en kabré con las versiones de torch==1.4.0 y torchvision==0.5.0 funcionan bien! El siguiente reto es con Zylo verdad? jaja ese me ha dado mucha guerra
